services:
  - type: worker
    name: myobfuscator
    env: node
    plan: free
    region: oregon

    buildCommand: npm install
    startCommand: node np/index.js


    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
